### ISSUE TITLE
Can't Run on System with only .Net 2.0

### ISSUE THREAD

**Issue by 0xdf-0xdf** [rasta-mouse/Watson#3] opened 2018-10-26 13:28 UTC
I've been unable to build this to run on a system with .net 2.0. Is it possible to build to run on older .NET frameworks?

**Comment by rasta-mouse** [comment] 2018-10-26 16:03
Looks like this is probably due to the introduction of Linq in #1 [here](https://github.com/rasta-mouse/Watson/pull/1/files#diff-1fae513d36f31b276e33472bb029854fR3).

Not sure if @mark-s has thoughts on this?  I should've noticed it before merging.
If not, I'll have a look at replacing it for something that's 2.0 compliant.

**Comment by mark-s** [comment] 2018-10-26 16:10
@rasta-mouse can look into this this weekend if you like? You're probably right about the cause - simple enough to replace the LINQ with a foreach/for.
.Net 2 though .. that's quite old!

**Comment by rasta-mouse** [comment] 2018-10-26 16:21
That would be awesome.

I know 2.0 sucks.  It's so we can target older machines like 2K8, assuming they haven't had newer versions installed - basically a backwards compatibility thing.

**Comment by 0xdf-0xdf** [comment] 2018-10-26 19:23
Yeah, I was just trying to use it on a 2k8 (ctf) target and ran into it there. But I feel like I run into old stuff all the time at work with only 2.0. Would be useful for old stuff.

**Comment by rasta-mouse** [comment] 2018-10-27 10:23
Merged #4

**Closed as completed by rasta-mouse** 2018-10-27 10:23 UTC

**Comment by KenP97** [comment] 2021-06-16 21:42
this still would build for .Net2.0
